### ISSUE TITLE
incorrect example in README

### ISSUE THREAD

**Issue by hmoffatt** [yaroslavche/BitMask#34]
In the README, you have

```
$mask ^= EXECUTE; // remove a single bit from the $mask
```

This does not remove a single bit in the general case - xor toggles it. It only removes it if you know it's already set.

The general way to remove is

```
$mask &= ~EXECUTE;
```

**Comment by yaroslavche** [comment]
Thank you for pointing this out! You’re absolutely right - XOR (`^=`) toggles the bit, rather than reliably removing it. To ensure that a bit is removed, the correct approach is to use `&= ~`EXECUTE.

I wasn’t aware of this distinction, so I’ll check the code to see how it’s currently behaving and make corrections if necessary. I’ll also update the README to reflect this more accurate method. I appreciate your attention to detail and for bringing this to my attention!

**Comment by hmoffatt** [comment]
I checked the code already, and it appears to test that the bit is set before toggling it, so this works OK. But you have the other version in there in the comments. https://github.com/yaroslavche/BitMask/blob/main/src/BitMask.php#L41
